# general settings
# CMD:
# .\train.py -opt .\options\train\CLIPIQA\train_CLIPIQA_KIQ20.yml --auto_resume

name: 001_CLIPIQA_RN50_KIQ20_Galaxy A53
model_type: GeneralIQAModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123

# dataset and data loader settings
datasets:
  train:
    name: KIQ20
    type: GeneralNRDataset
    dataroot_target: ../datasets/KK_dataset/KIQ20_images
    meta_info_file: ../datasets/meta_info/meta_info_KIQ20Dataset_Galaxy A53.csv
    split_file: ../datasets/meta_info/KIQ20Dataset_Galaxy A53.pkl
    mos_max: 100

    augment:
      hflip: true
      random_crop: 384 
    img_range: 1

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: KIQ20
    type: GeneralNRDataset
    dataroot_target: ../datasets/KK_dataset/KIQ20_images
    meta_info_file: ../datasets/meta_info/meta_info_KIQ20Dataset_Galaxy A53.csv
    split_file: ../datasets/meta_info/KIQ20Dataset_Galaxy A53.pkl
    mos_max: 100

    num_worker_per_gpu: 4
    batch_size_per_gpu: 8

# network structures
network:
  type: CLIPIQA 
  model_type: clipiqa+_kk
  # backbone: ViT-L/14
  backbone: RN50
  pretrained: true
  pos_embedding: true

# path
path:
  pretrain_network_g: ./net_best.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim:
    type: Adam 
    lr: !!float 2e-3
  
  scheduler:
    type: CosineAnnealingLR
    T_max: 50 
    eta_min: 0

  total_iter: 2000000
  total_epoch: 50 
  warmup_iter: -1  # no warm up

  # losses
  mos_loss_opt:
    type: MSELoss
    loss_weight: !!float 1.0

  metric_loss_opt:
    type: PLCCLoss
    loss_weight: !!float 1.0

# validation settings
val:
  val_freq: !!float 500
  save_img: false
  pbar: true

  key_metric: srcc # if this metric improve, update all metrics. If not specified, each best metric results will be updated separately
  metrics:
    srcc:
      type: calculate_srcc

    plcc:
      type: calculate_plcc

# logging settings
logger:
  print_freq: 100
  save_latest_freq: !!float 1e3 
  log_imgs_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: True
